yagom-academy/ios-rock-paper-scissors

RockPaperScissors/RockPaperScissors.xcodeproj/xcuserdata/wonhee.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist, RockPaperScissors/RockPaperScissors.xcodeproj/xcuserdata/wonhee.xcuserdatad/xcschemes/xcschememanagement.plist, RockPaperScissors/RockPaperScissors/main.swift
팀으로 구현 전 개인으로 묵찌빠 구현한 코드입니다. 리뷰 부탁드립니다ㅎㅎ
=> 묵찌빠 step1 구현

RockPaperScissors/RockPaperScissors/main.swift
* 문제가 되었던 옵셔널 강제 추출 부분을 수정했습니다.
- input에 대해 상단에서 한 번에 옵셔널 바인딩을 했을 경우, 입력 없이 Enter를 했을 때, else 구문을 통과하지 않아서 각각 바인딩 했습니다.
* Step 2와의 호환을 위해 rockPaperScissors 함수로 묶는 작업을 수행했습니다.
=> Step 2 - 묵찌빠 구현

RockPaperScissors/RockPaperScissors/main.swift
가위바위보는 이기는 경우가 3가지로 정해져있으므로, 3가지 경우와 비교해서 일치하는 경우에는 승리, 입력 값과 1~3 범위안의 랜덤 값과 동일하면 무승부, 다를 경우 패배하는 형식으로 코드를 작성했습니다.
=> Step 1 - 가위바위보 구현

RockPaperScissors/RockPaperScissors.xcodeproj/project.pbxproj, RockPaperScissors/RockPaperScissors/main.swift
@AppleCEO 
- swift Guideline - naming이 어려웠습니다. 이름 짓는 좋은 팁이 있을까요?
- 첫 커밋 전에 빌드 테스트를 하지 못해서 제대로 코딩하고 있는지 확인하기 어려웠습니다. 좋은 방법이 있을까요?
=> [STEP1] - Wody, SJ

RockPaperScissors/RockPaperScissors/main.swift
@zieunv 
`Ian`과 함께 최대한 공식문서를 따르기 위해 고민을 해봤어요 !
RockScissorsPaperGame Class를 인스턴스로 만드는 것을 시작으로 presentGameMemu, startGame을 통해 동작 단위 구분을 위해 extension을 사용해 봤어요 (extension의 진정한 기능은 못쓰지만 단순하게 메인 동작과 서브 동작을 구분하기 위해서 사용했습니다.) 구조는 그림으로 한번 만들어봤어요 👀 
옵셔널 강제추출에 있어서 지양해야겠지만, checkedInput 메소드에 옵셔널 강제 추출 하는 `validArrays.first!` 부분이 있는데요. if 조건문 상위 부분에서 이미 값은 존재하며 무조건 1개라는 조건을 통과해서 강제 추출에 위험성이 없다고 판단해서 이렇게 작성했어요. 혹시 문제가 있을까요? 🙂
비겼을 경우 다시 게임을 시작하는 로직을 반복문이 아닌 메소드의 호출을 통한 로직으로 작성했는데 혹시 반복문과 비교하여 어떤 방식이 더 효율적이라고 할 수 있나요? 😃
=> [STEP 1] - Fezz, Ian 

RockPaperScissors/RockPaperScissors/main.swift
@seizze 
하이디 안녕하세요!😃
Hailey, 수킴입니다!
- 변수명 작성
- 숫자 1, 2, 3 가독성을 높이기 위해 scissor, rock, paper 변수에 저장
- 플로우차트를 그려봤는데 잘 그린건지 조언 얻고 싶어요!
- playRockPaperScissors 함수에 case 1, 2, 3 구문에서 강제 언래핑을 사용했는데 case를 통해 Int 값이 들어온다는 확신을 가지고 있어서 사용했는데 혹시 더 괜찮은 방법이 있을까요?
- if구문에서 실행문이 한줄일때 가독성때문에 조건문이랑 같은 줄에 써줬는데 따로 써주는게 맞는 방법인가요?
- 작은 프로젝트에서 나중에 코드 유지보수 및 확장성까지 고려해서 작성하는 게 맞나요?(예를 들어, 함수를 기능별로 더 세세하게 나눈다거나 변수가 3개있으면 배열로 작성 또는 enum으로 열거 등등)
=> [STEP 1] Hailey, 수킴

RockPaperScissors/RockPaperScissors/main.swift
@zieunv 
---
`Ian`과 함께 [STEP 2]를 완성해 봤어요 🤔
- 열거형, 구조체
데이터를 정리하기 위해 열거형을 썼었고, `rawValue` 을 정리하기 위해 구조체를 이용했어요. 하지만 굳이 쓰지 않아도 될 것같은 코드를 중복시키다 보니 비효율적이라고 생각이 들기 시작해서, 오류제어를 위한 열거형만 남기고 구조체로 통합했어요 ➕
---
```swift
struct WinLoseDrawOfUserAtRockScissorsPaper {
static let userSelectWinRockScissors = 1
static let userSelectWinScissors = -2
static let userSelectLoseScissorsRock = -1
static let userSelectLosePaper = 2
static let userSelectDraw = 0
}
let userWinStatus = [WinLoseDrawOfUserAtRockScissorsPaper.userSelectWinRockScissors, WinLoseDrawOfUserAtRockScissorsPaper.userSelectWinScissors]
let computerWinStatus = [WinLoseDrawOfUserAtRockScissorsPaper.userSelectLoseScissorsRock, WinLoseDrawOfUserAtRockScissorsPaper.userSelectLosePaper]
```
`1, -2, -1, 2, 0` 과 같은 숫자를 정리하기 위해 구조체를 위와 같이 구성하고 사용자, 컴퓨터 …
=> [STEP 2] Fezz, Ian

RockPaperScissors/RockPaperScissors/main.swift
reviewer: @delmaSong  
코드를 작성할 때 고민되었던 점: 함수이름, 함수기능 분리
해결이 되지 않은 점: 옵셔널 강제추출하고 싶지 않았으나 방법을 몰라 오류발생 방지를 위해 강제추출 했습니다.
조언을 얻고 싶은 부분 등 상세하게 작성: 19번줄 옵셔널을 안전하게 추출하는 법, 35~37번줄 문자열 입력안되게 하는 법, 띄어쓰기 체크 등
깃이 아직 서툴러서 PR보내는데 오래 걸렸습니다.
기다리게해서 죄송합니다.
그럼 잘 부탁드립니다.
=> [STEP 1] Summer, Yun[4A]

README.md, RockPaperScissors/RockPaperScissors/main.swift
@YebinKim 
비비 안녕하세요!!
리뷰 잘 부탁드릴게요😄
먼저 어제 알려준 컴퓨터와 유저에 대해 구조체를 짜보는 부분은 현재 풀리퀘에는 반영을 못했어요. 생각해봤는데 잘 안돼서 step2에서 진행할 때 구현해보도록 하겠습니다!
현재 playRound 함수의 코드를 보면 아래처럼 guard let을 사용했는데요.
이렇게 수정 하기 전에는 강제 언래핑을 통해 enum의 인스턴스를 추출했었습니다.
이때  `RockScissorsPaper` 에 존재하지 않는 rawValue로 초기화를 한다면 nil이 생겨 문제가 생기지 않겠지만 여기서는 userInput이 1-3인것을 검증했고, 랜덤숫자도 1-3만 들어가기 때문에 문제가 생기지 않을거 같아 아래 수정 전 코드처럼 `!`를 사용했었는데요. 
`!`를 사용하면 안된다는 제약사항때문에 현재코드로 수정했습니다.
nil이 안나올거라는 확신이 있어도 강제 언래핑을 쓰면 안되는 건지 궁금합니다!!
제가 스스로 생각해본 결론은 코드의 수정이 있을때(userInput의 값이 변경될때) 문제가 생길 수 있어서 guard let으로 처리하는게 좋다고 생각했는데 이렇게 생각하면 될지도 궁금합니다!
```swift
//playRound() 현재 코드
guard let userChoice = RockScissorsPaper(rawValue: userInput),
let computerChoice = RockScissorsPaper(rawValue: Int.random(in: 1...3))
else {
return
}
let result = whoIsWinner(userChoice: …
```
=> ios-rock-paper-scissors [STEP 1] hosinging, terry

README.md, RockPaperScissors/RockPaperScissors/main.swift
@SungPyo 
안녕하세요 내일날씨맑음!! step-1을 완성하여 풀리퀘스트를 보냅니다!! 잘 부탁드려요 :)
열거형의 원시 값 저장과 사용법을 잘 몰라 찾아보며 공부했습니다.
게임 흐름 제어에서 막혀서 재귀를 사용하여 해결했습니다
한가지의 기능만 하도록 함수를 나누도록 노력했습니다.
열거형을 사용하여 rawvalue값을 이용하여 해결하였습니다.
``` swift 
func checkGameResult(user: RockPaperScissors, computer: RockPaperScissors) {
if user == computer {
gameResult = .draw
}
switch user {
case .scissors:
if computer == .paper {
gameResult = .win
}
case .rock:
if computer == .scissors {
gameResult = .win
}
case .paper:
if computer == .rock {
gameResult = .win
}
case .etc:
printError()
}
}
```
처음에 위와 같은 로직을 사용했다가 현재의 로직으로 바꾸었습니다.
위의 방법이 더 명확하게 표현 했다고 생각을 하고 바뀐 코드는 간결하게 표현했다고 생각하는데
어떤 방법이 더 괜찮은지 여쭤보고 싶습니다!
처음에 이 함수의 이름을 checkGameResult() 라고 지어줬습니다.
무언가를 체크한다 라는 함수네이밍을 사용할 경우에 Bool값을 반환하는 것이 이름에 맞다고 생각하여 바꾸었습니다.
하지만 함수의 내용은 결국 누가 이겼는지 판단해주는 …
=> 묵찌빠 게임 [Step 1] shapiro, jamking

README.md, RockPaperScissors/RockPaperScissors/main.swift
@SungPyo 
안녕하세요! 팀 4B의 Yun과 Yescoach 입니다. 이번 프로젝트 Review를 맡아주셔서 감사합니다.
프로젝트 진행에 앞서 UML과 의사코드, 순서도를 작성해보았습니다.
1. 재귀함수에 관하여
- startGame()에서 compare()를 호출하고, compare()에서는 비길 경우 다시 startGame()을 호출하는 구조로 작성하였는데, 이 구조가 바람직한지 잘 모르겠습니다.
- 재귀함수랑 반복문의 장단점은 무엇인가요?? 
2. 네이밍에 대한 조언
- 네이밍에 대한 고민을 많이 했는데, 적절한 네이밍이 였는지 잘 모르겠습니다.
ex) 사용자의 입력을 받는 함수 >> inputUserHand() -> choiceUserHand()
3. mutating에 대한 의견
- 구조체에서 mutating의 사용은 최대한 지양하신다고 하셨는데 그 이유가 궁금합니다!!
4. 중첩타입을 쓰는 이유에 대해서 궁금합니다.
- ex) 구조체 RockScissorsPaper 내에서 enum 타입을 선언하는 경우와 구조체 외부에서 선언하는 경우의 차이? 장단점이 궁금합니다.
=> 묵찌빠 게임 [Step 1] yescoach, yun

README.md, RockPaperScissors/RockPaperScissors/main.swift
@leejun6694 
- 플로우차트에서 optional 처리에 대한 내용을 포함시키는지 궁금합니다
- Swift에서도 상수를 담는 변수의 이름을 대문자로 구성된 snake case로 지어도 되나요? (ex. `EXIT_NUMBER`)
- 함수명이 return으로 시작해도 되나요? (ex. returnUserInput)
- 해당 프로젝트에서 Struct나 Class와 같은 사용자 정의 타입을 어떻게 활용할 수 있을지 궁금합니다.
- 과제에서 Naming이 가장 어려운 부분이었는데 적절하게 사용했는지 조언을 부탁드립니다!
- 가위바위보 모든 경우의 수에 대해 처리하기 번거로웠는데 아래와 같은 규칙을 찾아 적용하게 되었습니다.
- 가위바위보를 숫자로 변경(`가위: 1, 바위: 2, 보: 3`)했고 사용자값과 컴퓨터값의 차이가 다음과 같을 때 승, 패, 무승부를 판단하도록 했습니다:
- `1 또는 -2`: 사용자 승
- `2 또는 -1`: 컴퓨터 승
- `0`: 무승부 (아래 함수에서는 default로 처리)
```swift
func playRockScissorsPaperWith(
computerChoice: RockPaperScissors,
userChoice: RockPaperScissors
) -> GameResult {
let numberGap: Int = userChoice.rawValue - computerChoice.rawValue
switch numberGap {
case 1, -2:
return GameResult.win
case 2, -1:
return GameResult.lose …
```
=> 묵찌빠 게임 [STEP 1] Jost, Joey

README.md, RockPaperScissors/RockPaperScissors/main.swift
@YebinKim 
비비 풀리퀘스트 올렸어요.
리뷰 잘 부탁드립니다.
- 호싱잉
1. Enum안에 예를들면 가위바위보, 묵찌빠의 케이스가 있을 때 가위바위보에서 턴 결정 및 승자를 결정하는 것과  묵찌빠 값의 변화에 따라  턴 결정 및 승자 결정하는 것을 Computed Property를 선언해서 결정하게 하거나, 프로퍼티 옵저버를 통해 할 수 있지 않을까 고민을 해봤습니다. 이런 방식으로의 처리가 가능할지와 이런 방식으로 처리를 하게 된다면 발생할 수 있는 문제점들이 있을지...궁금합니다. 
PR하는 현재는 curly brace가 2개가 넘어가는 것 같고, 태리의 코드가 좋아 그대로 진행을 해봤고, 진행해보고자 했던 부분들에 대해서는 PR후 따로 해볼 예정입니다. PR후 피드백받고나서 이런 부분에 대해서 말씀 주실 내용이 있으시다면 말씀 나눠보고 싶습니다.
2. 현재 저희의 코드에서는 RockPaperScissors Enum을 활용해서 턴과 승자가 결정됐을 때 RockPaperScissors Enum을 활용해 묵찌빠의 숫자입력의 값을 변환해주어 묵찌빠에서 낸 숫자로 인식하게 만들었는데요. 이러한 방식과 각 각의 Enum을 따로 만들어서 사용하는 방법이 있을 것 같은데 이것은 단순한 선택인건지, 협업을 위해서는 따로 빼주는 것이 맞을지 고민을 해봤습니다.
- 테리
1. 현재 Game이라는 구조체를 만들고 여기서만 쓰이는 enum이 세개 있는데요.
Game 구조체 내부에서만 사용되기 때문에 내부로 넣어서 선언했는데 위치가 맞는지 궁금합니다.
---
2. 함수 개선사항
play함수 내부에
```swift …
```
=> 묵찌빠 게임 [Step2] hosinging, terry 

README.md, RockPaperScissors/RockPaperScissors/main.swift
안녕하세요 라자냐! 수정하고 싶은 부분이 있어서 다시 PR합니다. 감사합니다. @wonhee009 
1. step1에서 사용한 flow chart에서 최대한 벗어나지 않도록, 단순하게 회로를 짜기위해 노력했습니다. 그러다보니 몇가지 전역변수가 추가되었는데 이렇게 전역변수를 추가하는 것이 앱의 구동에 영향을 미치는지 궁금합니다.
2. 함수나 변수를 효율적으로 중복 없이 짜는 것과 두개로 나누더라도 명확한 의미전달을 통해 추후에 읽을 때 효과적인 리딩을 도모하는 것 둘 중에 어느 것이 더 중시되어야 할까요? (e.g.) (1)  userTurn이라는 전역변수와 computerTurn이라는 전역변수는 가위바위보의 승패가 결정나고 난 후에는 서로 반대되는 값을 가지기 때문에 하나만 있어도 코드의 구동에는 아무런 영향이 없습니다. 하지만 두개가 공존할 경우 나중에 확인하면 좀 더 직관적일 수 있다는 생각을 했습니다. (2) guard let 이 포함된 함수를 2개 써서 각각 가위바위보용, 묵찌빠용으로 구분하여 명백하게 동작을 구분하는 것이 나을지 아니면 저희가 작성한 코드 처럼 guard let 이 포함된 함수에서 새로운 함수를 불러내서 흐름제어를 통해 동작을 구분하는 것이 나을까요?
3. 스텝1에서 여쭤보았던 return startGame() 과 그냥 재귀함수로 startGame()을 하는 것의 차이를 알아내지 못했습니다. 우선 Return을 써서 했는데 차이가 있을까요?
4. switch 구문과 if 문을 둘다 사용해보았는데 if 문이 조건의 설정을 추가하여 제약을 더 부여할 수 있다느 관점에서는 더 편리했지만 …
=> 묵찌빠 게임 [step2] EHD, Geon

README.md, RockPaperScissors/RockPaperScissors/main.swift
@daheenallwhite 
1. 전역 상수
자주 사용되는 메시지들은 전역상수로 미리 선언해놓았습니다. 이렇게 하면 재사용성도 높아질 것이고 나중에 수정하기도 편해질 것이라고 생각했기 때문입니다. 이러한 작성 방식이 괜찮은 것인가요? (만약 괜찮다면 1, 2, 3이라는 가위바위보 숫자와 0이라는 종료 조건도 미리 상수로 선언해 놓으면 좋을 것 같습니다.)
2. 함수
원래는 "사용자로부터 입력을 받는 receiveInputFromUser함수"와 "입력을 받은 값이 적절한 값인지 구분하는 receiveAndJudgeUserInput함수"가 따로 작동하는 형태였는데, 입력값이 잘못된 경우 다시 입력받아야 하는 조건때문에 receiveAndJudgeUserInput함수가 receiveInputFromUser함수를 호출하는 형태가 되어버렸습니다. receiveInputFromUser함수가 존재하는 현재의 코드에 대해서 어떻게 생각하시나요? 없애야 할까요? 
3. Naming
이름을 정말 열심히 고민하여 작성하였는데 혹시 수정이 필요하다고 보이는 부분이 있나요?? 😭
1. gameResultTable 2차원 배열
사용자와 컴퓨터의 가위바위보 결과 경우의 수를 2차원 배열로 표현하였습니다. 행은 사용자에 해당되고, 열은 컴퓨터에 해당되는데 연산과 의미 전달의 효율성 제고를 위해 사용하였습니다.
2. receiveAndJudgeUserInput()
사용자가 잘못 입력한 경우 다시 입력을 받아야 하는데 이 부분을 반복문을 쓰지 않고 재귀형태로 구현하였습니다. 들여쓰기에 대한 조건때문도 있지만 코드의 가독성과 간결함 면에서 …
=> 묵찌빠 게임 [STEP 1] Nala, Coden

README.md, RockPaperScissors/RockPaperScissors/main.swift
@ye-ha 
step 1 PR입니다.
decideWinner 함수 구현 시 지금 구현해놓은 index를 활용하는 방법과 아래와 같이 tuple을 활용하는 방법 두가지 중 어떤 방법이 나을지 고민하였습니다.
```
func decideWinner1() {
let computerNumber = String(Int.random(in: 1...3))
let userNumber = checkValidity()
let tuple: (String, String) = (computerNumber, userNumber)
switch tuple {
case ("1","2"),("2","3"), ("3","1"):
print("이겼습니다!")
case ("1","1"), ("2","2"), ("3","3"):
print("비겼습니다!")
default:
print("졌습니다!")
}
}
```
그리고, 출력 시 게임 종료 후에 ()가 출력되는데 어떤 부분을 수정해야할지 여쭤보고 싶습니다.
=> 묵찌빠 게임 [Step 1] marisol, cathy

RockPaperScissors/RockPaperScissors/main.swift
@forestjae 
* enum에 원시값 타입을 다른 enum 타입을 넣으려고 했는데 오류가 생겼습니다. xcode 의 에러 문구를 보니 리터럴로만 원시값 타입을 설정할 수 있다는 것을 알게 되었습니다.
* 네이밍을 컨벤션을 따라 정확하게 정하려고 노력했습니다.
* 커밋 단위를 작게 하려고 노력했습니다.
* 함수를 작게 만드려고 노력했습니다.
* 저희 코드에 만약에 고차함수를 활용한다면 어디서 사용할 수 있을지 궁금합니다. 조언 부탁드려요.
* 코드 로직에 더 좋은 방법이 있는지 궁금합니다. 가위바위보 클래스를 만든다면 묵찌빠가 상속을 받아서 더 간결한 코드가 될지 고민입니다.
* 커밋 메시지 중에 동일한 부분이 있는데 괜찮은지 확인 부탁드립니다.
=> 묵찌빠 게임 [Step2] donnie, Tiana

RockPaperScissors/RockPaperScissors/main.swift
안녕하세요 애플사이다! 묵찌빠 게임 STEP2 진행했습니다.
**함수 분리에 관하여**
```swift
func playGame() {
let exitNumber = "0"
print(MessegePrint.menuDisplay, terminator: "")
let (userInput, userInputNumber) = makeRockScissorsPaper()
if userInputNumber == exitNumber {
print(MessegePrint.prgramExitMessege)
} else {
startGame(userInput)
}
}
func startGame(_ userInput: Hand?) {
guard let userInput = userInput else {
print(MessegePrint.inputErrorMessege)
playGame()
return
}
let userResult = playRockPaperScissors(userHand: userInput)
startMukJiPa(userResult: userResult)
}
```
위의 코드 처럼 `playGame()` 에서 `startGame()`을 분리하는 게 좋을지,
``` swift
func startMukJiPa(userResult: MatchResults) {
var userResult = userResult
let exitNumber = "0"
printTurn(userResult)
let (userInput, userInputNumber) = makeMukJiPa()
if userInputNumber == …
```
=> 묵찌빠[STEP2] papri, taeangel 

README.md, RockPaperScissors/RockPaperScissors/main.swift
@dnwhd0112
안녕하세요 우롱차!
저희는 seohyeon2, KayAhnDS 입니다.
묵찌빠 게임 STEP1 PR 요청 드립니다!
잘 부탁 드립니다!!
- printUserOption()
- “가위, 바위, 보, 종료”  출력
- makeComputerRandomNumber() -> Int
- 1이상 3이하의 랜덤한 수를 반환
- inputUserNumber() -> Int
- printUserOption()을 기본적으로 출력하고
- 사용자로부터 입력받은 후 checkUserInputNumber를 통해 입력에 해당하는 숫자를 반환
- checkUserInputNumber(userInput: String) -> Int
- 문자열을 입력 받고 스위치문을 통해 분기 처리 및 값 반환
- printErrorMessage()
- “잘못된 입력입니다. 다시 시도해주세요.” 출력
- compareTwoNumbers (userInput: Int, computerInput: Int) -> Int
- 사용자가 이기는 케이스를 선언.
- 사용자와 컴퓨터가 비기는 케이스, 사용자가 이기는케이스, 사용자가 지는 케이스를 검사 후 해당 값 반환.
- printResult(matchResult: Int)
- 매개변수로 받은 matchResult에 따라 스위치문으로 분기 처리 후 해당 문구 출력
- startGame()
- 게임을 시작하는 함수
- 먼저 컴퓨터의 숫자를 입력 받고
- 무한 루프를 돌면서 사용자 입력이..
- -1 인 경우 다시 입력 요구.
- 0 인 경우 종료.
- 1에서 3사이의 값은 컴퓨터의 숫자와 비교
- …
=> 묵찌빠 게임 [STEP1] seohyeon2, KayAhnDS

README.md, RockPaperScissors/RockPaperScissors.xcodeproj/project.pbxproj, RockPaperScissors/RockPaperScissors/RockPaperScissors.swift, RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift, RockPaperScissors/RockPaperScissors/main.swift
안녕하세요 도니! @westeastyear
묵찌빠 게임 STEP 1 PR 보냅니다!
---
- 세 명이서 짝 프로그래밍을 하게 되어 <**드라이버-네비게이터-옵저버**>로 역할을 분리해 커밋 단위로 돌아가면서 진행하기
* 저녁이 있는 삶 지향 - 7시 전까지 가급적 그날의 작업을 끝냅시다!
* 10시 30분에 모여서 간단히 스크럼을 진행합시다.
* 파일 하나당 하나의 클래스/구조체만 작성합시다.
* 관련이 있는 기능은 한 줄 개행, 관련이 적고 플로우 차트 상에서 분리되어 있는 기능은 두 줄 개행합시다.
* 클래스나 구조체를 만들 때, 각각의 메서드가 가지는 성질에 따라 extension을 통해 분리해서 관리합시다.
* 캡슐화에 신경씁시다.
* 커밋은 하나의 기능 혹은 함수를 기준으로 작성합시다.
* karma 스타일에 기반하여 접두어를 붙이고, 한글로 작성합시다.
* 짝 프로그래밍의 단위 또한 하나의 커밋 단위와 일치시켜서, 하나의 기능 혹은 함수를 구현한 뒤에 역할을 바꿉시다.
<br/>
요구서를 명시된 팀원들과 다시 정독하며 코드의 흐름을 신경쓰며 Flow Chart를 작성했습니다.
<br/>
`RockPaperScissorsGame`에서 사용자의 선택(`userSelection`)과 컴퓨터의 선택(`computerSelection`) 프로퍼티를 사용하며 초기화가 필요한 것을 알았습니다. 이니설라이저와 고민하다가 옵셔널 타입으로 선언하는 방법으로 해결했습니다.
<br/>
활동확습에서 캡슐화를 배워 미흡하지만 적용해보려 노력했습니다. `RockPaperScissorsGame`에서만 사용하는 메서드는 …
=> 묵찌빠 게임 [ STEP 1 ] 웡빙, 나이든별, Judy
